ARG COMPRESSOR_IMAGE="docker.io/alpine:3.22.1@sha256:4bcff63911fcb4448bd4fdacec207030997caf25e9bea4045fa6c8c44de311d1"
ARG DISTROLESS_IMAGE="quay.io/quarkus/quarkus-distroless-image:2.0-2025-07-20@sha256:0f6a2e0da65b3ae06ddfb4f5eff031dff9bed0f331c1b3140f8cb3cdc114d7fe"

FROM ${COMPRESSOR_IMAGE} AS compressor
ARG UPX_INSTALLATION_COMMAND="apk add \
    libgcc=14.2.0-r6 \
    libstdc++=14.2.0-r6 \
    upx=5.0.2-r0 \
  && rm -rf /var/cache/apt/*"
ARG UPX_COMPRESSION_MODE="--fast"

USER root
WORKDIR /project
RUN eval "${UPX_INSTALLATION_COMMAND}"
COPY \
  --chmod=700 \
  target/*-runner /project/application
RUN upx \
  "${UPX_COMPRESSION_MODE}" \
  -o application-compressed \
  application

FROM ${DISTROLESS_IMAGE} AS runner
ARG APP_DIR=/deployment
ARG UID=1001

USER root
WORKDIR ${APP_DIR}
# Include if the project has .so that need to be copied:
# COPY \
#  --chmod=444 \
#  target/*.so /lib/
COPY \
  --from=compressor \
  --chmod=111 \
   /project/application-compressed ${APP_DIR}/application

ENV LANGUAGE='en_US:en'
USER ${UID}:${UID}
ENTRYPOINT [ "./application" ]
